### ISSUE TITLE
Quarterly Installment Plans" + Netsuite Invoicing

### ISSUE THREAD

**Issue by DavidMuller** [cooncesean/upaya-tech-spec#12]
How does netsuite "email invoicing" work in the case of people who pay us in quarterly installments?

On our end, when someone agrees to "buy an object" and "pay in quarterly installments", we create 4 records (**approximately**) like...
- `ItemPayment` for $125. Pays for service from Jan 1st 2016 - Mar 31st 2016. Payment due Feb 1st 2016.
- `ItemPayment` for $125. Pays for service from April 1st 2016 - Jun 30th 2016. Payment due May 1st 2016.
- `ItemPayment` for $125. Pays for service from July 1st 2016 - Sept 30th 2016. Payment due August 1st 2016.
- `ItemPayment` for $125. Pays for service from Oct 1st 2016 - Jan 1st 2017. Payment due Nov 1st 2016.

Does Netsuite know about each of these "quarterly dues"? How do we describe such a situation to netsuite so that netsuite "chases people down" appropriately?

**Comment by cooncesean** [comment]
@DavidMuller do you have an answer to this?

**Comment by DavidMuller** [comment]
In the above situation we'd create 4 separate Invoice objects in Netsuite; the finance team will control the dunning process on those 4 Invoices
